project:
  type: website
  output-dir: docs

website:
  title: "Ian Gault"
  site-url: https://iangault.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: projects/index.qmd
        text: Projects
      - href: scientific-communication.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/iangault
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/iangault
        aria-label: LinkedIn

format:
  html:
    theme:
      - flatly
      - darkly
    css: styles.css
    toc: true

editor:
  render-on-save: true
