project:
  type: website
  output-dir: docs

website:
  title: "Ian Gault"
  site-url: https://iangault.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scientific-communication.qmd
        text: Publications
      - href: blog/index.qmd
        text: Blog
      - text: Projects
        menu:
          - href: projects/index.qmd
            text: All Projects
          - href: projects/water-quality/index.qmd
            text: Water Quality
          - href: projects/dashboards/index.qmd
            text: Dashboards
          - href: projects/machine-learning/index.qmd
            text: Machine Learning
    right:
      - icon: github
        href: https://github.com/iangault
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/iangault
        aria-label: LinkedIn

format:
  html:
    theme: litera
    css: styles.css
    toc: false

editor:
  render-on-save: true
