project:
  type: website
  output-dir: docs

website:
  title: "MDS Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: test_slides.qmd
        text: Slides

format:
  html:
    theme:
      - flatly
      - darkly
      #- brand
    css: styles.css
    toc: true

editor:
  render-on-save: true



